# Generated by Django 6.0.6 on 2026-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='attempt_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
